export const addisAbabaCenter = [9.03, 38.74];

export const sampleLocations = [
  {
    caseId: "hana-bekele",
    lat: 9.03,
    lng: 38.74,
    name: "Hana Bekele",
    age: 14,
    city: "Addis Ababa",
    status: "Critical",
    lastSeen: "Piassa, Addis Ababa, 2 hours ago",
    sightingsCount: 4,
    avatarTone: "from-[#dc2626] to-[#f59e0b]",
  },
  {
    caseId: "samuel-tadesse",
    lat: 11.5942,
    lng: 37.3908,
    name: "Samuel Tadesse",
    age: 11,
    city: "Bahir Dar",
    status: "Active",
    lastSeen: "Lakeside district, Bahir Dar, today at 10:15",
    sightingsCount: 2,
    avatarTone: "from-[#2563eb] to-[#60a5fa]",
  },
  {
    caseId: "mimi-alemu",
    lat: 7.0621,
    lng: 38.4763,
    name: "Mimi Alemu",
    age: 9,
    city: "Hawassa",
    status: "Critical",
    lastSeen: "Lake Hawassa area, yesterday evening",
    sightingsCount: 5,
    avatarTone: "from-[#b91c1c] to-[#fb7185]",
  },
  {
    caseId: "yonas-hailu",
    lat: 13.4967,
    lng: 39.4753,
    name: "Yonas Hailu",
    age: 16,
    city: "Mekelle",
    status: "Resolved",
    lastSeen: "Adi Haki, Mekelle, today at 07:40",
    sightingsCount: 1,
    avatarTone: "from-[#16a34a] to-[#86efac]",
  },
  {
    caseId: "rahel-girma",
    lat: 8.9806,
    lng: 38.7578,
    name: "Rahel Girma",
    age: 13,
    city: "Addis Ababa",
    status: "Active",
    lastSeen: "Bole, Addis Ababa, yesterday at 18:20",
    sightingsCount: 3,
    avatarTone: "from-[#1d4ed8] to-[#93c5fd]",
  },
  {
    caseId: "bereket-kassa",
    lat: 11.6004,
    lng: 37.3833,
    name: "Bereket Kassa",
    age: 10,
    city: "Bahir Dar",
    status: "Active",
    lastSeen: "Kebele 14, Bahir Dar, this morning",
    sightingsCount: 2,
    avatarTone: "from-[#1d4ed8] to-[#93c5fd]",
  },
  {
    caseId: "eden-mekonnen",
    lat: 7.0504,
    lng: 38.4953,
    name: "Eden Mekonnen",
    age: 12,
    city: "Hawassa",
    status: "Resolved",
    lastSeen: "Industrial zone road, Hawassa, last night",
    sightingsCount: 1,
    avatarTone: "from-[#16a34a] to-[#86efac]",
  },
  {
    caseId: "natnael-gebru",
    lat: 13.4889,
    lng: 39.4575,
    name: "Natnael Gebru",
    age: 15,
    city: "Mekelle",
    status: "Critical",
    lastSeen: "Ayder area, Mekelle, yesterday at 16:30",
    sightingsCount: 6,
    avatarTone: "from-[#dc2626] to-[#f59e0b]",
  },
];
